import { Dimensions, StyleSheet } from "react-native";
import color from "./color";
export default StyleSheet.create({
  container: { flex: 1 },
  centerBox: {
    flex: 1,
    flexDirection: "column",
    alignContent: "center",
    justifyContent: "center",
    padding:"5%",
    borderRadius: 2,
    //backgroundColor: "red"
  },
  centerBoxWithoutPadding: {
    flex: 1,
    flexDirection: "column",
    alignContent: "center",
    justifyContent: "center",
    //padding:"5%",
    //borderRadius: 2,
    //backgroundColor: "red"
  },
  scrollViewCenter: { flexGrow: 1, justifyContent: "center" },
  // arrowBox: { backgroundColor: '#f5f5f5', borderBottomColor: '#b2b1b1', borderBottomWidth: 1, borderColor: '#f5f5f5', paddingLeft: 5 },
  // imageContainer: { width: '100%', marginTop: 10, paddingTop: 40, paddingBottom: 20, borderColor: '#b2b1b1', borderWidth: 0.5, },
  boxContent: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    
  },
  descriptionBox: {
    width: "90%",
   flex: 1,
    marginLeft: "5%",
    MarginTop: "1%",
    marginLeft: "5%",

  },
  reviewHeader: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  pickerItem: { marginTop: 10, marginRight: 4, marginBottom: 10, },
  shadow: {
    shadowColor: "#000",
    borderWidth: 1,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderTopEndRadius: 10,
    borderBottomEndRadius: 10,
    borderBottomLeftRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.27,
    shadowRadius: 1.55,
    elevation: 2,
  },
  wealthShadow: {
    borderRadius: 5,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 1,
  },

  passiveBox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    justifyContent: "flex-end",
    marginRight: 20,
  },
  snapBox: {
    width: "49%",
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 5,
    paddingBottom: 10,
  },
  downBorder: { borderBottomWidth: 1, paddingLeft: 5 },

  pickerBorder: { borderBottomWidth: 1, }, bottomdownBorder: { borderBottomWidth: 0.5, },
  calendarBox: { width: '48%', paddingTop: 10, paddingLeft: 10, paddingBottom: 30, paddingRight: 5, borderRadius: 5, marginTop: 10, marginLeft: 3, marginRight: 3 },

  snapBox_1: {
    width: "48%",
    paddingTop: 25,
    paddingLeft: 15,
    paddingRight: 5,
    paddingBottom: 10,
    marginBottom: 8,
    borderRadius: 5,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 2.12,
    shadowRadius: 2.22,
    elevation: 2.5,
  },
  skeletonSnapBox: {
    width: "48%",
    paddingTop: 25,
    paddingLeft: 15,
    paddingRight: 5,
    paddingBottom: 10,
    marginBottom: 8,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 2.12,
    shadowRadius: 2.22,
    elevation: 2.5,
  },
  // arrowBox: { backgroundColor: '#f5f5f5', borderBottomColor: '#b2b1b1', borderBottomWidth: 1, borderColor: '#f5f5f5', paddingLeft: 5 },
  listBox: {
    //marginTop: 15,
    borderRadius: 5,
    padding: 10,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 2.12,
    shadowRadius: 2.22,
    elevation: 1.8,
  },
  transcationListBox: {
    borderRadius: 5,
    padding: 10,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 2.12,
    shadowRadius: 2.22,
    elevation: 1.8,
  },
  snapView: { borderRadius: 5, elevation: 1, borderColor: 1 },
  bill_box: {
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 2.12,
    shadowRadius: 2.22,
    elevation: 3,
    padding: 5,
    borderRadius: 10,
  },
  shadow_box: {
    borderRadius: 5,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 2.12,
    shadowRadius: 2.22,
    elevation: 3,
    shadowColor: color.myOrangeColor.color,
  },
  transaction_box: {
    borderRadius: 5,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  bill_shadow_box: {
    borderRadius: 5,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 0.22,
    shadowColor: "rgba(255,165,0,1)",
    elevation: 3,
  },
  amenityBox: { width: 80,
    height: 80,
    margin: "2%",
    //padding: "2%" , 
    justifyContent: "center",},

  radius: { borderRadius: 5, borderWidth: 1 },
  winningRadius: { borderRadius: 5, height: 25, borderWidth: 1, marginTop: 5 },

  detailsBox: {width: "95%", 
  height: "90%",
   //backgroundColor: "pink",
   alignSelf: "center",
   padding: "1%",
   flex: 1,
  },
  simpleBox: {
    margin: "5%",
  },
  horizontalBox: {
    flexDirection: 'row', 
    justifyContent: 'space-between',
  }
  
});
