import { StyleSheet, Appearance } from "react-native";
export default StyleSheet.create({
  grayColor: { color: "#999" },
  // blackColor:{color:"#000000"},
  buttonclr:{backgroundColor:"#003366"},
  grayBackColor: { backgroundColor: "#999" },
  grayBorderColor: { borderColor: "#999" },
  backColor: { backgroundColor: "#307EA0" },
  linkColor: { color: "#307EA0" },
  linkBorderColor: { borderColor: "#000000" },
  calendarBackColor: { backgroundColor: '#2f9ac9' },
  textWhiteColor: { color: "#fff" },
  whiteBackground: { backgroundColor: "#ffffff" },
  WhiteBorder: { borderColor: "#fff" },
  inputBackground: { backgroundColor: "#F5F5F5" },
  borderInputColor: { borderColor: "#f5f5f5" },
  pickerColor: { color: "#f5f5f5" },
  calenderBorderColor: { borderColor: '#7d7d84' },
  pickerBottomBorder: { borderBottomColor: "#F5F5F5" },
  borderBottomColor: { borderBottomColor: "#b2b1b1" },
  dollarColor: { backgroundColor: "#1c7aa2" },
  settingsButton: { backgroundColor: "#fffdf8" },
  settingsButtonBorder: { borderColor: "#dfe3e9" },
  orangeColor: { color: "#fc9200" },
  myOrangeColor: {color: "#fc9200"},
  orangeBorder: {borderColor: "#fc9200", borderWidth: 1},
  settingsItem: { color: "#303333" },
  placeHolder: { color: "#7b7878" },
  blueColor: { color: '#1b79a1' },
  borderBlue: { borderColor: '#1b79a1' },
  backgroundBlue: { backgroundColor: '#1b79a1' },
  darkgrayColor: { color: "#666666" },
  greenTextColor: { color: '#008255' },
  greenBackgroundColor: { backgroundColor: '#008255' },
  greenBorderColor: { borderColor: '#008255' },
  profitColor: { color: "#109593" },
  profitBackground: { backgroundColor: "#109593" },
  profitButtonColor: { borderColor: "#109593" },
  lossColor: { color: "#f15b27" },
  lossButtonColor: { borderColor: "#f15b27" },
  yellowColor: { color: '#f8bb32'},
  yellowBackColor: { backgroundColor: '#f8bb32' },
  textColor: { color: "#6a6d6d" },
  pickerBackColor: { backgroundColor: "#f3f3f3" },
  headerText: { color: "#636363" },
  buttonText: { color: "#c5d0d3" },
  buttonBorder: { borderColor: "#c5d0d3" },
  buttonBackground: { backgroundColor: "#c5d0d3" },
  goalTextColor: { color: "#4a4a4a" },
  passiveText: { color: "#15212a" },
  moneyText: { color: "#adadad" },
  shadowBorderColor: { borderColor: "#c0cbcd" },
  shadowColor: { shadowColor: "#000" },
  blackColor: /* Appearance.getColorScheme() === "dark"? { color: "white"}: */ {  color: "#000" },
  passiveBorder: { borderColor: "#007ea0" },
  passiveBackground: { backgroundColor: "#007ea0" },
  nonPassiveBorder: { borderColor: "#109593" },
  nonPassiveBackground: { backgroundColor: "#109593" },
  winningPickerBorder: { borderColor: "#e0e0e0", backgroundColor: "#e0e0e0" },
  dangerBackgroundColor: { backgroundColor: "#ee5a28" }, dangerColor: { color: '#ee5a28' },
  blueBorder: { borderColor: "#007fa1" },
  blueTopBorder: { borderTopColor: '#007fa1' },
  blueBottomBorder: { borderBottomColor: '#007fa1' },
  blueBackground: { backgroundColor: "#007fa1" },
  lossingBorder: { borderColor: "#f4511e" },
  lossingBackgroundColor: { backgroundColor: "#f4511e" }, lightBorderColor: { borderColor: '#d3d3d3' },
  lightGrayBackColor: { backgroundColor: "#f4f4f4" },
  profitBackColor: { backgroundColor: "#109593" },
  lossBackColor: { backgroundColor: "#f15b27" },
  blackShadowColor: { shadowColor: "#000" },
  lightGrayBack: { backgroundColor: "#fafafa" },
  lightGray: { color: "#fafafa" },
  disconnectedColor: { color: "#af2a27" },
  connectedColor: { color: "#2ca959" },
  redColor: { color: "#f4222b" },
  redBackColor: { backgroundColor: "#f4222b" },
  redBorderColor: { borderColor: "#f4222b" },
  downBorderColor: { borderColor: "#dcdfe0" },
  alertBackColor: { backgroundColor: "rgba(244,34,43,0.3)" },
  planCircleBorder: { borderColor: "#2eccc8" },
  planCircleBackground: { backgroundColor: "#2eccc8" },
  greyText: { color: "#b8b8b8" },
  optionsBlue: { color: "#0F6FDD" },
  calendarPopupBackground: { color: '#fef6f3' },
  greenColor: { backgroundColor: "#3d962b" },
  borderErrorBottomColor: { borderBottomColor: "#f4222b" },
  coachGreyLeftBorder: { borderLeftColor: '#c8c8c8' }, coachGreyRightBorder: { borderRightColor: '#c8c8c8' },
  lightBlack: {color: "#515151"}
});
